name: get_bootimg_from_payload.bin...

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://bigota.d.miui.com/21.11.24/miui_ARES_21.11.24_bf9b3a2526_12.0.zip
  ZIP_NAME: Ares
  TZ: Asia/Shanghai

jobs:
  make:
    runs-on: ubuntu-latest

    steps:

    - name: install Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
    - name: Initialization environment 
      run: |
        cd ~
        pip install bsdiff4
        python -m pip install protobuf

    - name: Clean Up Disk Space
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean 
        
    - name: Clone the tools source code
      run: |
       cd ~
       git clone https://github.com/vm03/payload_dumper.git
       
  
    - name: Download the ROM
      run: |
       cd ~
       wget -O rom.zip $ROM_URL
   
    - name: unzip the ROM
      run: |
       cd ~
       unzip *.zip -d payload_dumper
    
    - name: extract the payload.bin
      run: |
       cd ~
       cd payload_dumper
       python payload_dumper.py payload.bin
       mkdir temp
       sudo cp -r payload_dumper/$ZIP_NAME.zip temp
   

    
    - name: Upload the bootimg to WeTransfer
      run: |
        cd temp
        curl --upload-file $Zip_name https://transfer.sh/"$Zip_name"
